<html>
<body>
<div>
<p>Hi,</p>
<p>&nbsp;</p>

<p>A nomination for the Awards for Excellence 2016-17 under the category has been submitted to you for approval. As the sponsor of the nomination, kindly act on the same here .</p>

<p><a href="http://sparsh-ic/ic/afe-2016Ang/ang/index.asp#/Sponsor">Click on this link to view the details</a> </p>
<p>&nbsp;</p>
<p>Regards,</p>
<p>Team Awards for Excellence 2016-17</p>
</div>
</body>
</html>